### ISSUE TITLE
Resource

### ISSUE THREAD

**Issue by deadhead103** [jbuitt/nwws-php-client#1]
This is exactly what I was looking for, thanks!  But one question, do you know what resource I should be attaching to?  If I don't use a resource it seems the only message I receive is the *WARNING* message when you first logon.  The only chat room I can find is nwws@conference.nwws-oi.weather.gov and it doesn't seem to give me anything but "body" and a bunch of "CDATA" tags.

**Comment by jbuitt** [comment]
It shouldn't really matter what resource you use, I've used different several strings in the past, and it seems to be arbitrary. However, I'm guessing your problem is not related to the resource. I recently found an issue with the PHP client where the 'on_groupchat_message' event is no longer emitted, and therefore doesn't trigger the appropriate callback. There must have been a change with either the JAXL library or the NWWS-OI server, but unfortunately I haven't had any time to research it further. I'll let you know when I figure it out.  Thanks!

**Comment by deadhead103** [comment]
So a little more information.  I switched to the Perl client and have it installed on a Google Cloud Linux box, works really well.  But when NWSS sends a message, it really only contains a "header" which is just a description.  I've included a capture from today via your Perl application..... 
[kohx_wfus54-torohx.172156_14914793.txt](https://github.com/jbuitt/nwws-php-client/files/900935/kohx_wfus54-torohx.172156_14914793.txt)
I'm going to guess the alert from the NOAA website is gone by the time you read this so I saved their XML file....
[kohx_wfus54-torohx.172156_14914793_XML.txt](https://github.com/jbuitt/nwws-php-client/files/900941/kohx_wfus54-torohx.172156_14914793_XML.txt)
This is the actual CAP message with all the important details.  I'm told there is a way to receive this from NWWS-OI but I can't figure it out.  When I inquired to NWWS about providing any documentation they had, they sent this link...https://xmpp.org/extensions/xep-0020.pdf
The CAP data is really important to me because of the polygon information which shows the area of the alert.  I'm really new on XMPP but it seems like there is almost a "hidden" data form that has to be requested to get ALL the XML data but maybe not.

**Comment by deadhead103** [comment]
I deleted previous comment, what I thought was there was not.  I downloaded the NWS End User Client and the information downloaded matches perfectly to your archive dumps.  Very impressive work considering the amount of code you used.

**Comment by jbuitt** [comment]
Thank you!  I got another chance to look at the PHP client today, and I was reminded why it's not working. When I enable debugging and print out the XMMP stanzas, it shows that the XML is not  properly formatted, and therefore the JAXL library isn't able to parse it.  I'll hack on it some more this weekend to see if I can get it working.

**Comment by jbuitt** [comment]
I ended up rewriting the client using a different XMPP PHP library. It now properly connects to NWWS-OI and downloads products as before. Please let me know if you have any problems. Thanks!
