### ISSUE TITLE
Client Crashes: PHP Warning:  fread(): supplied resource is not a valid stream resource in /home/dev/nwws-php-client/vendor/fabiang/xmpp/src/Stream/SocketClient.php on line 154

### ISSUE THREAD

**Issue by rcmcdonald91** [jbuitt/nwws-php-client#2]
Client runs for many minutes without issue. I get products populating in the archive folder and logs. However, after several minutes, the script crashes.

`PHP Warning:  fread(): supplied resource is not a valid stream resource in /home/dev/nwws-php-client/vendor/fabiang/xmpp/src/Stream/SocketClient.php on line 154
`

PHP 7.0.28-0ubuntu0.16.04.1

**Comment by jbuitt** [comment]
I'm aware of the issue, this problem is with the Fabiang XMPP library and how it interfaces with the NOAA Weather Wire servers. I haven't found a PHP XMPP library that works reliably.

If you want to something that works better, check out my nwws-python-client repo.

Jim
